# ~/.config/starship.toml
# ref: https://starship.rs/config/

[aws]
format='[${symbol}_($profile)_($region)(\[$duration\])]($style) '
symbol="â˜ï¸"

[cmd_duration]
format="[$duration]($style) "
min_time=0
show_milliseconds=true
style="cyan bold"

[git_branch]
format="[$symbol$branch(:$remote_branch)]($style) "
truncation_length=30

[git_commit]
only_detached=false

[java]
format='[${symbol}_(${version})]($style) '
symbol='â˜•'

[package]
format='[${symbol}_$version]($style) '
symbol='ğŸ“¦'

[python]
format='[${symbol}_${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
symbol='ğŸ'
style="green bold"

[time]
format="[$time]($style) "
time_format = "%T%.3f"
disabled=false
